"""empty message

Revision ID: b8b8d677ec95
Revises: 
Create Date: 2019-04-01 12:41:46.515972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b8d677ec95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('realm', sa.String(length=24), nullable=True),
    sa.Column('region', sa.String(length=24), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_creation_date'), 'guild', ['creation_date'], unique=False)
    op.create_index(op.f('ix_guild_update_date'), 'guild', ['update_date'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('realm', sa.String(length=24), nullable=True),
    sa.Column('region', sa.String(length=24), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_creation_date'), 'character', ['creation_date'], unique=False)
    op.create_index(op.f('ix_character_update_date'), 'character', ['update_date'], unique=False)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('guild_followers',
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_creation_date'), 'post', ['creation_date'], unique=False)
    op.create_index(op.f('ix_post_update_date'), 'post', ['update_date'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('region', sa.String(length=24), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roster_creation_date'), 'roster', ['creation_date'], unique=False)
    op.create_index(op.f('ix_roster_update_date'), 'roster', ['update_date'], unique=False)
    op.create_table('roster_member',
    sa.Column('roster_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_member')
    op.drop_index(op.f('ix_roster_update_date'), table_name='roster')
    op.drop_index(op.f('ix_roster_creation_date'), table_name='roster')
    op.drop_table('roster')
    op.drop_index(op.f('ix_post_update_date'), table_name='post')
    op.drop_index(op.f('ix_post_creation_date'), table_name='post')
    op.drop_table('post')
    op.drop_table('guild_followers')
    op.drop_table('followers')
    op.drop_index(op.f('ix_character_update_date'), table_name='character')
    op.drop_index(op.f('ix_character_creation_date'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_guild_update_date'), table_name='guild')
    op.drop_index(op.f('ix_guild_creation_date'), table_name='guild')
    op.drop_table('guild')
    # ### end Alembic commands ###
